=== UO294066/sew/xml/circuito.dtd
<!ELEMENT circuito (referencia+, foto+, video*, coordenada+, tramo+)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT coordenada (#PCDATA)>
<!ELEMENT tramo (coordenada+)>
<!ATTLIST circuito
    nombre CDATA #REQUIRED
	longitud CDATA #REQUIRED
    longitud_unidades CDATA #REQUIRED
    anchura CDATA #REQUIRED
    anchura_unidades CDATA #REQUIRED
    fecha CDATA #REQUIRED
    hora CDATA #REQUIRED
    vueltas CDATA #REQUIRED
    localidad CDATA #REQUIRED
    pais CDATA #REQUIRED>
<!ATTLIST referencia ref CDATA #REQUIRED>
<!ATTLIST foto ref CDATA #REQUIRED>
<!ATTLIST video ref CDATA #REQUIRED>
<!ATTLIST coordenada
    longitud CDATA #REQUIRED
	latitud CDATA #REQUIRED
	altitud CDATA #REQUIRED>
<!ATTLIST tramo
    distancia CDATA #REQUIRED
    unidades CDATA #REQUIRED
	sector CDATA #REQUIRED>

=== UO294066/sew/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">
<circuito nombre="Circuito de las Américas" longitud="5513" longitud_unidades="km" anchura="15" anchura_unidades="m" fecha="20-10-2024" hora="22:00" vueltas="56" localidad="Austin" pais="Estados Unidos">
    
    <referencia ref="https://es.wikipedia.org/wiki/Circuito_de_las_Am%C3%A9ricas"></referencia>
    <referencia ref="https://www.dazn.com/es-ES/news/motor/circuito-de-las-americas-cota-donde-esta-como-es-caracteristicas-como-llegar-y-fotos-del-escenario-del-gp-del-mundial-de-f1-y-motogp/1fpu8eh1poemg1pkvrd0rkxkce"></referencia>
    <referencia ref="https://www.circuitosdecarreras.com/estados-unidos/circuito-americas/"></referencia>

    <foto ref="Panorama.png"></foto>
    <foto ref="Meta.jpg"></foto>

    <coordenada latitud="30.1335220°" longitud="-97.6422641°" altitud="170" altitud_unidades="m"></coordenada>

    <tramo distancia="633.7" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1300383°" longitud="-97.6370485°" altitud="182.3887205" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="21.41" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1300258°" longitud="-97.6368383°" altitud="182.3887205" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="20.04" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1302000°" longitud="-97.6367794°" altitud="182.3887205" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="160.17" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1315694°" longitud="-97.6373092°" altitud="169.5425525" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="31.22" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1318476°" longitud="-97.6373411°" altitud="169.5425525" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="30.54" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1321144°" longitud="-97.6372938°" altitud="166.4426245" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="33.06" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1323818°" longitud="-97.6371504°" altitud="165.6159755" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="39.03" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1326377°" longitud="-97.6368661°" altitud="166.4426245" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="180.04" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1326377°" longitud="-97.6368661°" altitud="166.4426245" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="26.47" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1336582°" longitud="-97.6350727°" altitud="166.9248699" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="61.81" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1341727°" longitud="-97.6348123°" altitud="166.9248699" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="23.5" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1343580°" longitud="-97.6346870°" altitud="166.7073935" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="39.71" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1345312°" longitud="-97.6343255°" altitud="166.7073935" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="31.74" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1346411°" longitud="-97.6340184°" altitud="166.3677553" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="21.61" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1347778°" longitud="-97.6338530°" altitud="166.3677553" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="22.78" distancia_unidades="m" sector="1">
        <coordenada latitud="30,1349675°" longitud="-97.6337536°" altitud="166.3116165" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="19.2" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1351439°" longitud="-97.6337248°" altitud="166.3116165" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="26.51" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1353863°" longitud="-97.6336895°" altitud="165.7915452" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="25.42" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1356047°" longitud="-97.6336048°" altitud="165.7915452" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="30.53" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1358281°" longitud="-97.6334158°" altitud="165.7915452" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="27.91" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1359847°" longitud="-97.6331903°" altitud="165.7915452" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="32.62" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1361217°" longitud="-97.6328928°" altitud="167.6638630" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="29.92" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1361795°" longitud="-97.6325908°" altitud="167.6638630" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="25.95" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1361605°" longitud="-97.6323229°" altitud="167.6638630" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="49.05" distancia_unidades="m" sector="1">
        <coordenada latitud="30.1359837°" longitud="-97.6318559°" altitud="167.6638630" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="56.88" distancia_unidades="m" sector="2">
        <coordenada latitud="30.1357626°" longitud="-97.6313230°" altitud="167.7025002" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="16.83" distancia_unidades="m" sector="2">
        <coordenada latitud="30.1357238°" longitud="-97.6311579°" altitud="167.7025002" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="14.85" distancia_unidades="m" sector="2">
        <coordenada latitud="30.1357617°" longitud="-97.6310105°" altitud="167.7025002" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="39.23" distancia_unidades="m" sector="2">
        <coordenada latitud="30.1359692°" longitud="-97.6306808°" altitud="166.6214304" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="44.96" distancia_unidades="m" sector="2">
        <coordenada latitud="30.1362563°" longitud="-97.6303513°" altitud="167.2596297" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="25.45" distancia_unidades="m" sector="2">
        <coordenada latitud="30.1364442°" longitud="-97.6301997°" altitud="168.7943359" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="22.35" distancia_unidades="m" sector="2">
        <coordenada latitud="30.1365712°" longitud="-97.6300205°" altitud="168.7943359" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="22.16" distancia_unidades="m" sector="2">
        <coordenada latitud="30.1366221°" longitud="-97.6297962°" altitud="168.7943359" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="20.69" distancia_unidades="m" sector="2">
        <coordenada latitud="30.1365965°" longitud="-97.6295862°" altitud="173.0697661" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="18.66" distancia_unidades="m" sector="2">
        <coordenada latitud="30.1365326°" longitud="-97.6294092°" altitud="173.0697661" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="14.05" distancia_unidades="m" sector="2">
        <coordenada latitud="30.1364436°" longitud="-97.6293039°" altitud="173.0697661" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="13.6" distancia_unidades="m" sector="2">
        <coordenada latitud="30.1363408°" longitud="-97.6292249°" altitud="173.0697661" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="15.17" distancia_unidades="m" sector="2">
        <coordenada latitud="30.1362225°" longitud="-97.6291447°" altitud="173.0697661" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="16.01" distancia_unidades="m" sector="2">
        <coordenada latitud="30.1361642°" longitud="-97.6288767°" altitud="173.0697661" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="167.89" distancia_unidades="m" sector="2">
        <coordenada latitud="30.1364838°" longitud="-97.6271633°" altitud="177.4382764" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="14.84" distancia_unidades="m" sector="2">
        <coordenada latitud="30.1365241°" longitud="-97.6270176°" altitud="177.4382764" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="17.22" distancia_unidades="m" sector="2">
        <coordenada latitud="30.1366346°" longitud="-97.6268881°" altitud="171.8399461" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="366.13" distancia_unidades="m" sector="2">
        <coordenada latitud="30.1392024°" longitud="-97.6244949°" altitud="168.9580539" altitud_unidades="m"></coordenada>
    </tramo>

    <tramo distancia="17.39" distancia_unidades="m" sector="2">
        <coordenada latitud="30.1393572°" longitud="-97.6245041°" altitud="168.9580539" altitud_unidades="m"></coordenada>
    </tramo>
